--Q-17. write a SQL query to determine the maximum order (purchase) amount generated by each salesperson. 
--Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.). 
--Return salesperson id and maximum purchase amount.
use assignment4
select salesman_id,max(purch_amt) as maximum 
from Tbl_Orders
group by salesman_id
having salesman_id between 5003 and 5008